[package]
org = "ballerina"
name = "http_advanced_tests"
version = "2.8.4"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.8.4"

[[platform.java11.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.8.4.jar"
