resources:
  - h1_h1_passthrough.yaml
  - ingress.yaml
  - netty-backend.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: h1-h1-passthrou-deployment
