[package]
org = "ballerina"
name = "http_security_tests"
version = "2.7.19"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.7.19"

[[platform.java11.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.7.19.jar"
