[package]
org = "ballerina"
name = "http_dispatching_tests"
version = "2.12.2"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.12.2"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.12.2-SNAPSHOT.jar"
