[package]
org = "ballerina"
name = "http_dispatching_tests"
version = "2.6.0"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.6.0"

[[platform.java11.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.6.0-SNAPSHOT.jar"
