[package]
org = "ballerina"
name = "http"
version = "2.2.0"
authors = ["Ballerina"]
keywords = ["http", "network", "service", "listener", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-http"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/http-native-2.2.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/mime-native-2.2.0-20220124-205900-b566652.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.46.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-classes-2.0.46.Final.jar"

[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"

[[platform.java11.dependency]]
path = "./lib/testng-7.4.0.jar"
