[plugin]
id = "http-compiler-plugin"
class = "io.ballerina.stdlib.http.compiler.HttpCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/http-compiler-plugin-2.12.1.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.1.0.jar"
