[package]
org = "ballerina"
name = "http_interceptor_tests"
version = "2.14.0"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.14.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.14.0-SNAPSHOT.jar"
