resources:
  - h1_transformation.yaml
  - ingress.yaml
  - netty-backend.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: h1-transformati-deployment
