[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/mime" = "@stdlib.mime.version@"
"ballerina/auth" = "@stdlib.auth.version@"
"ballerina/cache" = "@stdlib.cache.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/crypto" = "@stdlib.crypto.version@"
"ballerina/file" = "@stdlib.file.version@"
"ballerina/reflect" = "@stdlib.reflect.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/task" = "@stdlib.task.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "http"
    version = "@project.version@"
    path = "../http-native/build/libs/http-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["http", "http-tests"]

    [[platform.libraries]]
    artifactId = "mime-native"
    version = "@stdlib.mimenative.version@"
    path = "./lib/mime-native-@stdlib.mimenative.version@.jar"
    groupId = "ballerina"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-common"
    version = "@netty.version@"
    path = "./lib/netty-common-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-buffer"
    version = "@netty.version@"
    path = "./lib/netty-buffer-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-transport"
    version = "@netty.version@"
    path = "./lib/netty-transport-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-resolver"
    version = "@netty.version@"
    path = "./lib/netty-resolver-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-handler"
    version = "@netty.version@"
    path = "./lib/netty-handler-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-codec-http"
    version = "@netty.version@"
    path = "./lib/netty-codec-http-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-codec"
    version = "@netty.version@"
    path = "./lib/netty-codec-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-handler-proxy"
    version = "@netty.version@"
    path = "./lib/netty-handler-proxy-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-codec-http2"
    version = "@netty.version@"
    path = "./lib/netty-codec-http2-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "commons-pool"
    version = "@commmon.pool.version@"
    path = "./lib/commons-pool-@commmon.pool.version@.jar"
    groupId = "commons-pool.wso2"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "snakeyaml"
    version = "@snakeyaml.version@"
    path = "./lib/snakeyaml-@snakeyaml.version@.jar"
    groupId = "org.wso2.orbit.org.yaml"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "bcprov-jdk15on"
    version = "@bouncycastle.version@"
    path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"
    groupId = "org.bouncycastle"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "bcpkix-jdk15on"
    version = "@bouncycastle.version@"
    path = "./lib/bcpkix-jdk15on-@bouncycastle.version@.jar"
    groupId = "org.bouncycastle"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static"
    version = "@tcnative.version@"
    path = "./lib/netty-tcnative-boringssl-static-@tcnative.version@.jar"
    groupId = "io.netty"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "mimepull"
    version = "@mimepull.version@"
    path = "./lib/mimepull-@mimepull.version@.jar"
    groupId = "org.jvnet.mimepull"
    modules = ["http"]

    [[platform.libraries]]
    artifactId = "org.testng"
    version = "@testng.version@"
    path = "./lib/testng-@testng.version@.jar"
    groupId = "org.testng"
    modules = ["http-tests"]
