[package]
org = "ballerina"
name = "http"
version = "1.1.0-alpha5"

[[platform.java11.dependency]]
path = "../http-native/build/libs/http-native-1.1.0-alpha5-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "http"
version = "1.1.0-alpha5-SNAPSHOT"


[[platform.java11.dependency]]
path = "./lib/mime-native-1.1.0-alpha5-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "mime-native"
version = "1.1.0-alpha5-SNAPSHOT"


[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.50.Final.jar"
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "4.1.50.Final"


[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"
groupId = "commons-pool.wso2"
artifactId = "commons-pool"
version = "1.5.6.wso2v1"


[[platform.java11.dependency]]
path = "./lib/snakeyaml-1.26.0.wso2v1.jar"
groupId = "org.wso2.orbit.org.yaml"
artifactId = "snakeyaml"
version = "1.26.0.wso2v1"


[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.61.jar"
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "1.61"


[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.61.jar"
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "1.61"


[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.31.Final.jar"
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "2.0.31.Final"


[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"


[[platform.java11.dependency]]
path = "./lib/testng-6.14.3.jar"
groupId = "org.testng"
artifactId = "org.testng"
version = "6.14.3"
