[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "cache"
version = "2.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-alpha5"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "oauth2"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-alpha5"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-alpha5"
