[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha2"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-alpha2"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-alpha2"
