[[dependency]]
org = "ballerina"
name = "http"
version = "@toml.version@"
version = "1.1.0-alpha3"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "file"
version = "@stdlib.file.version@"

[[dependency]]
org = "ballerina"
name = "auth"
version = "@stdlib.auth.version@"

[[dependency]]
org = "ballerina"
name = "mime"
version = "@stdlib.mime.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"
