[package]
org = "ballerina"
name = "http_client_tests"
version = "2.10.12"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.10.12"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.10.12-SNAPSHOT.jar"
