[package]
org = "ballerina"
name = "http_client_tests"
version = "2.11.3"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.11.3"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.11.3-SNAPSHOT.jar"
