[package]
org = "ballerina"
name = "http_misc_tests"
version = "2.13.0"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.13.0.jar"
