[package]
org = "ballerina"
name = "http_resiliency_tests"
version = "2.11.7"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.11.7"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.11.7.jar"
